# Generated by Django 3.2.5 on 2021-07-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ffghj', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
